apiVersion: v1
kind: Service
metadata:
  name: aem-publish
  namespace: aem-oak
  labels:
    app.kubernetes.io/name: aem-publish
    app.kubernetes.io/component: publish
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: aem-publish
